
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from '../components/BootstrapClient';
import "./styles/globals.css";
import Providers from "@/components/Providers";
/*import Navbar from "@/components/Navbar";*/
import AppHeader from '../components/AppHeader';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  /*const [menuOpen, setMenuOpen] = useState(false);
  const [showSignIn, setShowSignIn] = useState(false);*/

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preload" href="/npas-logo.png" as="image" />
        <link rel="preload" href="/astro-bg.png" as="image" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <>
          <BootstrapClient />
          <AppHeader />
          {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
